# Generated by Django 3.2.16 on 2025-03-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20230712_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentposts',
            options={'ordering': ('created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comentposts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comentposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария'),
        ),
        migrations.AlterField(
            model_name='comentposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_coment', to='blog.post', verbose_name='Публикация'),
        ),
    ]
